location            = "westeurope"
resource_prefix     = "digital-showroom"
app                 = "ds"
ddos_protection_plan_id = "/subscriptions/387c083d-834a-4607-92fa-ac786f0d42f3/resourceGroups/rg-sharedservices-prod-westeurope-001/providers/Microsoft.Network/ddosProtectionPlans/AzureDDosProtection-prod-001"
script_path = "../scripts"